// Coverage for U7 (docs/UndoRedo_Expansion_Implementation_Plan.md U7:
// シーン追加・画像更新) — the final Undo/Redo対象拡張 implementation unit:
// adding scene(s) via an already-open project's file picker (one
// <input multiple> file-selection batch = one undo unit, same design
// decision as U8's floorplan add) and replacing a scene's image (same
// simple applyXxx(id, value) shape as U1, extended to a paired
// {file, fileName} value).
//
// A project's very *first* file selection (empty -> non-empty, "open a
// project") is a load, not a trackable edit, and stays completely
// outside HistoryManager -- see applySceneAdd()'s comment in script.js.
// Every test below therefore loads its baseline scene(s) via that
// untracked path first (loadInitialScenes()), then exercises the
// tracked add-more-scenes path (addScenes()) separately.
//
// Image-binary retention mirrors the pattern already established for
// floorplans (U8) and the pre-existing scene delete/restore (U6): the
// scene object keeps its original `file` permanently (now also updated
// on image *replace*, not just add -- previously only blobUrl/fileName
// were updated there, leaving `file` pointing at the original upload
// forever); blobUrl/thumbUrl are disposable views regenerated from
// `file` whenever the scene becomes present again or its image changes.
//
// Image content is verified via the scene list's own thumbnail <img>
// (.scene-thumb, src is a deterministic canvas.toDataURL() JPEG
// generated by the app's own generateThumb()) rather than any new test
// hook -- the same "reuse an already-rendered, already-deterministic
// external observable" approach U8 used for the FloorMap canvas's own
// toDataURL().
const { test, expect } = require('@playwright/test');
const path = require('path');
const { gotoApp, expectNoErrors, dirtyIndicator, enterEditor } = require('./helpers');

const FIXTURES = path.join(__dirname, '..', 'fixtures');
const FIXTURE_A = path.join(FIXTURES, 'fixture-a.png');
const FIXTURE_B = path.join(FIXTURES, 'fixture-b.png');
const FIXTURE_C = path.join(FIXTURES, 'fixture-c.png');
const FLOORPLAN_1 = path.join(FIXTURES, 'lifecycle-scene-a.png');
const POS_A = { x: 70, y: 50 };

async function historyCounts(page) {
  return page.evaluate(() => ({
    undoCount: window.__historyManagerForTests.undoCount,
    redoCount: window.__historyManagerForTests.redoCount,
  }));
}

function sceneNames(page) {
  return page.locator('#scene-list .scene-item .scene-name').allTextContents();
}

function currentSceneName(page) {
  return page.locator('#current-scene-name').textContent();
}

function sceneItem(page, name) {
  return page.locator('#scene-list .scene-item').filter({ has: page.locator('.scene-name', { hasText: name }) });
}

// .scene-thumb's src is a deterministic data: URL (same crop math + JPEG
// quality every time, see generateThumb() in script.js) generated
// asynchronously after the underlying image loads -- poll rather than
// read immediately.
async function sceneThumbSrc(page, name) {
  const el = sceneItem(page, name).locator('.scene-thumb');
  await expect.poll(() => el.count()).toBeGreaterThan(0);
  await expect.poll(() => el.getAttribute('src')).not.toBeNull();
  return el.getAttribute('src');
}

function markerSceneNames(page) {
  return page.locator('#floormap-mk-list-ul .floormap-mk-list-scene').allTextContents();
}

async function loadInitialScenes(page, fixtures) {
  await enterEditor(page);
  await page.locator('#file-input').setInputFiles(fixtures);
  await expect(sceneNames(page)).resolves.toEqual(
    fixtures.map(f => path.basename(f, path.extname(f)))
  );
}

// Drives the same shared #file-input a second time, now that the
// project is non-empty -- exercises handleFiles()'s tracked
// (!wasEmpty) branch, same technique as loadInitialScenes() uses for
// the untracked one.
async function addScenes(page, fixtures) {
  await page.locator('#file-input').setInputFiles(fixtures);
}

async function deleteSceneByName(page, name) {
  await sceneItem(page, name).locator('.scene-delete-btn').click();
}

async function updateSceneImageByName(page, name, fixturePath) {
  await sceneItem(page, name).locator('.scene-replace-btn').click();
  await page.locator('#replace-scene-input').setInputFiles(fixturePath);
}

async function addFloorplan(page, fixturePath) {
  await page.locator('#add-floorplan-btn').click();
  await page.locator('#floorplan-input').setInputFiles(fixturePath);
}

async function enterSplit(page) {
  await page.locator('#split-compare-btn').click();
}

async function pickCompareScene(page, side, sceneName) {
  await page.locator(`#picker-btn-${side}`).click();
  await page.locator('.picker-item').filter({ hasText: sceneName }).click();
}

test.describe('Scene add / image update history (undo/redo)', () => {
  test('adding a scene to an already-open project pushes one history entry, marks dirty, and adds it to the list', async ({ page }) => {
    const errors = await gotoApp(page);
    await loadInitialScenes(page, [FIXTURE_A]);
    expect(await historyCounts(page)).toEqual({ undoCount: 0, redoCount: 0 });
    await expect(dirtyIndicator(page)).toBeHidden();

    await addScenes(page, [FIXTURE_B]);

    await expect(sceneNames(page)).resolves.toEqual(['fixture-a', 'fixture-b']);
    await expect(dirtyIndicator(page)).toBeVisible();
    expect(await historyCounts(page)).toEqual({ undoCount: 1, redoCount: 0 });

    expectNoErrors(errors);
  });

  test('undo removes the added scene entirely; redo restores the same id (same name/position) and the same image', async ({ page }) => {
    const errors = await gotoApp(page);
    await loadInitialScenes(page, [FIXTURE_A]);
    await addScenes(page, [FIXTURE_B]);
    expect(await historyCounts(page)).toEqual({ undoCount: 1, redoCount: 0 });
    const beforeThumb = await sceneThumbSrc(page, 'fixture-b');

    const undoResult = await page.evaluate(() => window.__historyManagerForTests.undo());
    expect(undoResult).toBe(true);
    expect(await historyCounts(page)).toEqual({ undoCount: 0, redoCount: 1 });
    await expect(sceneNames(page)).resolves.toEqual(['fixture-a']);
    await expect(dirtyIndicator(page)).toBeVisible(); // undo never auto-cleans

    const redoResult = await page.evaluate(() => window.__historyManagerForTests.redo());
    expect(redoResult).toBe(true);
    expect(await historyCounts(page)).toEqual({ undoCount: 1, redoCount: 0 });
    // Same id proxy: applySceneAdd()'s isPresent=true branch always
    // re-inserts the SAME captured object (by reference, from the
    // historyManager closure) at its original index -- never a rebuilt
    // copy -- so name + position + rendered image content matching is a
    // sufficient identity proof (same reasoning U8 relied on).
    await expect(sceneNames(page)).resolves.toEqual(['fixture-a', 'fixture-b']);
    expect(await sceneThumbSrc(page, 'fixture-b')).toBe(beforeThumb);

    expectNoErrors(errors);
  });

  test('a single multi-file selection is one undo unit: undo removes every scene from that batch together, redo restores all of them', async ({ page }) => {
    const errors = await gotoApp(page);
    await loadInitialScenes(page, [FIXTURE_A]);
    await addScenes(page, [FIXTURE_B, FIXTURE_C]);
    expect(await historyCounts(page)).toEqual({ undoCount: 1, redoCount: 0 });
    await expect(sceneNames(page)).resolves.toEqual(['fixture-a', 'fixture-b', 'fixture-c']);

    const undoResult = await page.evaluate(() => window.__historyManagerForTests.undo());
    expect(undoResult).toBe(true);
    await expect(sceneNames(page)).resolves.toEqual(['fixture-a']);

    const redoResult = await page.evaluate(() => window.__historyManagerForTests.redo());
    expect(redoResult).toBe(true);
    await expect(sceneNames(page)).resolves.toEqual(['fixture-a', 'fixture-b', 'fixture-c']);

    expectNoErrors(errors);
  });

  test('replacing a scene image pushes one history entry and marks dirty', async ({ page }) => {
    const errors = await gotoApp(page);
    await loadInitialScenes(page, [FIXTURE_A, FIXTURE_B]);
    expect(await historyCounts(page)).toEqual({ undoCount: 0, redoCount: 0 });

    await updateSceneImageByName(page, 'fixture-a', FIXTURE_C);

    expect(await historyCounts(page)).toEqual({ undoCount: 1, redoCount: 0 });
    await expect(dirtyIndicator(page)).toBeVisible();
    // scene id/name/position all preserved -- only the image changed.
    await expect(sceneNames(page)).resolves.toEqual(['fixture-a', 'fixture-b']);

    expectNoErrors(errors);
  });

  test('undo restores the old image; redo restores the new image; scene id, name, and list position never change', async ({ page }) => {
    const errors = await gotoApp(page);
    await loadInitialScenes(page, [FIXTURE_A, FIXTURE_B]);
    const oldThumb = await sceneThumbSrc(page, 'fixture-a');

    await updateSceneImageByName(page, 'fixture-a', FIXTURE_C);
    const newThumb = await sceneThumbSrc(page, 'fixture-a');
    expect(newThumb).not.toBe(oldThumb);

    const undoResult = await page.evaluate(() => window.__historyManagerForTests.undo());
    expect(undoResult).toBe(true);
    await expect(sceneNames(page)).resolves.toEqual(['fixture-a', 'fixture-b']); // name/position unchanged
    expect(await sceneThumbSrc(page, 'fixture-a')).toBe(oldThumb);

    const redoResult = await page.evaluate(() => window.__historyManagerForTests.redo());
    expect(redoResult).toBe(true);
    await expect(sceneNames(page)).resolves.toEqual(['fixture-a', 'fixture-b']);
    expect(await sceneThumbSrc(page, 'fixture-a')).toBe(newThumb);

    expectNoErrors(errors);
  });

  test('replacing the current scene\'s image immediately re-renders the panorama; current scene stays the same scene throughout', async ({ page }) => {
    const errors = await gotoApp(page);
    await loadInitialScenes(page, [FIXTURE_A, FIXTURE_B]); // loadInitialScenes leaves fixture-a current
    await expect(currentSceneName(page)).resolves.toBe('fixture-a');

    await updateSceneImageByName(page, 'fixture-a', FIXTURE_C);
    await expect(currentSceneName(page)).resolves.toBe('fixture-a');

    const undoResult = await page.evaluate(() => window.__historyManagerForTests.undo());
    expect(undoResult).toBe(true);
    await expect(currentSceneName(page)).resolves.toBe('fixture-a');

    expectNoErrors(errors);
  });

  test('marker and floorplan references to an added scene stay resolvable across the scene\'s own undo/redo', async ({ page }) => {
    const errors = await gotoApp(page);
    await loadInitialScenes(page, [FIXTURE_A]);
    await addFloorplan(page, FLOORPLAN_1);
    await addScenes(page, [FIXTURE_B]);

    await sceneItem(page, 'fixture-b').click(); // make fixture-b current
    await page.locator('#floormap-place-btn').click();
    await page.locator('#floormap-canvas').click({ position: POS_A });
    await page.locator('#floormap-place-btn').click();
    await expect(markerSceneNames(page)).resolves.toEqual(['fixture-b']);

    // Undo the marker placement (its own, separate entry) -> undo the
    // scene add -> both must cleanly disappear with no leftover error.
    let r = await page.evaluate(() => window.__historyManagerForTests.undo());
    expect(r).toBe(true);
    await expect(markerSceneNames(page)).resolves.toEqual([]);
    r = await page.evaluate(() => window.__historyManagerForTests.undo());
    expect(r).toBe(true);
    await expect(sceneNames(page)).resolves.toEqual(['fixture-a']);

    // Redo both back in order.
    r = await page.evaluate(() => window.__historyManagerForTests.redo());
    expect(r).toBe(true);
    await expect(sceneNames(page)).resolves.toEqual(['fixture-a', 'fixture-b']);
    r = await page.evaluate(() => window.__historyManagerForTests.redo());
    expect(r).toBe(true);
    await expect(markerSceneNames(page)).resolves.toEqual(['fixture-b']);

    expectNoErrors(errors);
  });

  // Regression-shaped test matching the exact class of bug U8's Required
  // Fix (PR #52 reviews #4893987323 / #4894418976) guarded against for
  // FloorMap add: a marker placed on a scene *after* that scene's own
  // add-entry was pushed must never survive if that same add-entry's
  // undo (not the marker's own undo) later makes the scene absent again.
  // Reaching this exact replay state through the app's own sequential
  // undo()/redo() isn't possible -- the marker's own later push always
  // truncates any pending redo/undo-ordering that would let the scene
  // add's undo run while the marker still exists in the normal stack
  // order -- so this captures the scene-add entry's own `undo` closure
  // directly off window.__historyManagerForTests's already-exposed
  // internal stack (historyManager itself, not a wrapper) right after
  // it's pushed, then invokes it directly once the marker exists,
  // exactly like a same-slot invocation would.
  test('undoing a scene add (via its own captured entry) removes markers placed on it afterward, never touching unrelated scenes/markers', async ({ page }) => {
    const errors = await gotoApp(page);
    await loadInitialScenes(page, [FIXTURE_A]);
    await addFloorplan(page, FLOORPLAN_1);

    // Unrelated marker on the untouched fixture-a scene -- must survive.
    await page.locator('#floormap-place-btn').click();
    await page.locator('#floormap-canvas').click({ position: POS_A });
    await page.locator('#floormap-place-btn').click();
    await expect(markerSceneNames(page)).resolves.toEqual(['fixture-a']);

    await addScenes(page, [FIXTURE_B]);
    await page.evaluate(() => {
      const hm = window.__historyManagerForTests;
      window.__staleSceneAddUndo = hm._undoStack[hm._undoStack.length - 1];
    });

    await sceneItem(page, 'fixture-b').click();
    await page.locator('#floormap-place-btn').click();
    await page.locator('#floormap-canvas').click({ position: { x: 170, y: 130 } });
    await page.locator('#floormap-place-btn').click();
    await expect(markerSceneNames(page).then(a => a.sort())).resolves.toEqual(['fixture-a', 'fixture-b']);

    await page.evaluate(() => window.__staleSceneAddUndo.undo());

    await expect(sceneNames(page)).resolves.toEqual(['fixture-a']);
    await expect(markerSceneNames(page)).resolves.toEqual(['fixture-a']); // fixture-b's marker gone, fixture-a's survives

    expectNoErrors(errors);
  });

  test('compare slot references stay valid after undoing the add of a scene currently assigned to a compare slot', async ({ page }) => {
    const errors = await gotoApp(page);
    await loadInitialScenes(page, [FIXTURE_A, FIXTURE_B]);
    await addScenes(page, [FIXTURE_C]);
    await enterSplit(page);
    await pickCompareScene(page, 'a', 'fixture-a');
    await pickCompareScene(page, 'b', 'fixture-c');

    const undoResult = await page.evaluate(() => window.__historyManagerForTests.undo());
    expect(undoResult).toBe(true);
    await expect(sceneNames(page)).resolves.toEqual(['fixture-a', 'fixture-b']);
    // No crash/error from a compare slot index left pointing past the
    // end of the shrunken scenes array; split view (still entered,
    // untouched by this undo) stays visible and usable.
    await expect(page.locator('#compare-container')).toBeVisible();

    expectNoErrors(errors);
  });

  test('a new scene-add or image-update operation after undo clears the redo stack', async ({ page }) => {
    const errors = await gotoApp(page);
    await loadInitialScenes(page, [FIXTURE_A]);
    await addScenes(page, [FIXTURE_B]);
    expect(await historyCounts(page)).toEqual({ undoCount: 1, redoCount: 0 });

    const undoResult = await page.evaluate(() => window.__historyManagerForTests.undo());
    expect(undoResult).toBe(true);
    expect(await historyCounts(page)).toEqual({ undoCount: 0, redoCount: 1 });

    await addScenes(page, [FIXTURE_C]);
    expect(await historyCounts(page)).toEqual({ undoCount: 1, redoCount: 0 });
    await expect(sceneNames(page)).resolves.toEqual(['fixture-a', 'fixture-c']);

    const redoResult = await page.evaluate(() => window.__historyManagerForTests.redo());
    expect(redoResult).toBe(false);
    await expect(sceneNames(page)).resolves.toEqual(['fixture-a', 'fixture-c']); // unchanged by the no-op redo

    expectNoErrors(errors);
  });

  test('Viewer mode: scene add and image replace stay blocked at the function level, and history/state stay untouched', async ({ page }) => {
    const errors = await gotoApp(page);
    await loadInitialScenes(page, [FIXTURE_A, FIXTURE_B]);
    expect(await historyCounts(page)).toEqual({ undoCount: 0, redoCount: 0 });

    // Editor -> Viewer while clean switches directly (no confirmation needed).
    await page.locator('#app-mode-toggle-btn').click({ force: true });
    await expect(page.locator('body')).toHaveClass(/mode-viewer/);

    // 1) Add: #file-input is always visually-hidden (not mode-gated by
    // CSS -- it's the same shared input a first "open a project" load
    // uses in Viewer mode), so driving it directly with a non-empty
    // project proves handleFiles()'s own assertEditorMode() guard at
    // the function level.
    await page.locator('#file-input').setInputFiles(FIXTURE_C);
    expect(await historyCounts(page)).toEqual({ undoCount: 0, redoCount: 0 });
    await expect(sceneNames(page)).resolves.toEqual(['fixture-a', 'fixture-b']); // unchanged

    // 2) Image replace: .scene-replace-btn carries .editor-only directly
    // (CSS-hidden in Viewer mode), but its click listener
    // (openReplaceScenePicker()) is still attached; dispatching a click
    // bypasses the CSS gate and proves the function-level guard
    // independently.
    const replaceBtn = sceneItem(page, 'fixture-a').locator('.scene-replace-btn');
    await expect(replaceBtn).toBeHidden();
    await replaceBtn.dispatchEvent('click');
    // openReplaceScenePicker() returns before ever opening the picker,
    // so #replace-scene-input never receives a file and no further
    // action is possible -- history/state stay untouched.
    expect(await historyCounts(page)).toEqual({ undoCount: 0, redoCount: 0 });

    await page.locator('#app-mode-toggle-btn').click({ force: true });
    await expect(page.locator('body')).toHaveClass(/mode-editor/);
    await expect(sceneNames(page)).resolves.toEqual(['fixture-a', 'fixture-b']); // still unchanged

    expectNoErrors(errors);
  });

  // Proves applySceneAdd() is id-scoped: a scene added after an earlier
  // entry was pushed must survive that earlier entry's own undo AND
  // redo completely unchanged -- same shape of regression the U6
  // required fix guarded against for scene reorder, and U8 for
  // FloorMap add.
  test('a scene added after an earlier entry survives that entry\'s undo and redo, unchanged', async ({ page }) => {
    const errors = await gotoApp(page);
    await loadInitialScenes(page, [FIXTURE_A]);
    await addScenes(page, [FIXTURE_B]); // entry #1
    await deleteSceneByName(page, 'fixture-b'); // entry #2
    await expect(sceneNames(page)).resolves.toEqual(['fixture-a']);

    await addScenes(page, [FIXTURE_C]); // entry #3, added AFTER entry #2 was pushed
    await expect(sceneNames(page)).resolves.toEqual(['fixture-a', 'fixture-c']);
    const cThumb = await sceneThumbSrc(page, 'fixture-c');

    // Undo entry #3 (C's own creation) -> must remove only C.
    let r = await page.evaluate(() => window.__historyManagerForTests.undo());
    expect(r).toBe(true);
    await expect(sceneNames(page)).resolves.toEqual(['fixture-a']);

    // Redo entry #3 -> C back, unchanged.
    r = await page.evaluate(() => window.__historyManagerForTests.redo());
    expect(r).toBe(true);
    await expect(sceneNames(page)).resolves.toEqual(['fixture-a', 'fixture-c']);
    expect(await sceneThumbSrc(page, 'fixture-c')).toBe(cThumb);

    expectNoErrors(errors);
  });
});
